/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export * from './exampleGetById';
export * from './exampleSearch';
export * from './response';
