/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Pagination {
  /**
   * Current page number
   *
   * @example 1
   */
  page?: number;
  /**
   * Number of items per page
   *
   * @example 10
   */
  pageSize?: number;
  /**
   * Total number of items available
   *
   * @example 100
   */
  totalCount?: number;
}
