/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ExampleDetail } from '.';

export interface ExampleGetById {
  params?: {
    /**
     * example shaw brand
     *
     * @example IAM
     */
    id: string;
  };
  query?: {
    /**
     * brand
     *
     * @example IAM
     */
    brand: string;
  };
  responses?: {
    /**
     * OK detail response
     */
    '200'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      data?: {
        /**
         * OK response
         */
        result?: ExampleDetail;
      };
    };
    /**
     * Error response
     */
    '400'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      error?: {
        /**
         * Error message
         *
         * @example Error: something went wrong
         */
        message?: string;
        /**
         * HTTP status code of the error
         *
         * @example 400
         */
        status?: number;
      };
    };
    /**
     * Error response
     */
    '404'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      error?: {
        /**
         * Error message
         *
         * @example Error: example not found
         */
        message?: string;
        /**
         * HTTP status code of the error
         *
         * @example 404
         */
        status?: number;
      };
    };
  };
}
