/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Pagination } from '../response';
import { ExampleCard } from '.';

/**
 * Retrieves an array of examples by ids
 */
export interface ExampleGetByIds {
  body?: {
    /**
     * Optional brand filter to narrow down the search results. If provided, it will filter examples by this brand.
     *
     * @example IAM
     */
    brand?: string;
    /**
     * An array of unique identifiers for the examples to search.
     *
     * @example
     * [
     *   "12345",
     *   "67890"
     * ]
     */
    ids: string[];
  };
  responses?: {
    /**
     * OK search response
     */
    '200'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      data?: {
        pagination?: Pagination;
        results?: ExampleCard[];
      };
    };
    /**
     * Error response
     */
    '400'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      error?: {
        /**
         * Error message
         *
         * @example Error: error occurred
         */
        message?: string;
        /**
         * HTTP status code of the error
         *
         * @example 400
         */
        status?: number;
      };
    };
    /**
     * Error response
     */
    '404'?: {
      /**
       * API version of the response
       *
       * @example v1.0
       */
      apiVersion?: string;
      error?: {
        /**
         * Error message
         *
         * @example Error: error occurred
         */
        message?: string;
        /**
         * HTTP status code of the error
         *
         * @example 404
         */
        status?: number;
      };
    };
  };
}
