/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ExampleCard {
  /**
   * Brand of the example
   *
   * @example IAM
   */
  brand?: string;
  /**
   * Unique identifier of the example
   *
   * @example 12345
   */
  id?: string;
  /**
   * Name of the example
   *
   * @example Example Name
   */
  name?: string;
}

/**
 * OK response
 */
export interface ExampleDetail {
  /**
   * Brand of the example
   *
   * @example IAM
   */
  brand?: string;
  /**
   * Unique identifier of the example
   *
   * @example 12345
   */
  id?: string;
  /**
   * Image URL
   *
   * @example https://example.com/image.jpg
   */
  image?: string;
  /**
   * Name of the example
   *
   * @example Example Name
   */
  name?: string;
}
