/* eslint-disable @typescript-eslint/no-explicit-any */
import { Pagination } from '../interfaces/joi-types/response' // This is an autogenerated type!

export const formatDetailResponse = (data: any) => {
  return {
    apiVersion: 'v1.0',
    data: {
      result: data,
    },
  }
}

export const formatSearchResponse = (
  data: any,
  pagination: Pagination,
  additionalInfo = {}
) => {
  return {
    apiVersion: 'v1.0',
    data: {
      results: data,
      pagination,
      ...additionalInfo,
    },
  }
}

export const formatErrorResponse = (message: string, status: number = 400) => {
  return {
    apiVersion: 'v1.0',
    error: {
      message,
      status,
    },
  }
}
